version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: minio-storage
    ports:
      - "${MINIO_PORT:-9000}:9000"
      - "${MINIO_CONSOLE_PORT:-9001}:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin123}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  file-server:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: file-server-api
    ports:
      - "${API_PORT:-8080}:8080"
    environment:
      - MINIO_ENDPOINT=minio:${MINIO_PORT:-9000}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY:-minioadmin}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY:-minioadmin123}
      - MINIO_BUCKET=${MINIO_BUCKET:-files}
      - SERVER_PORT=${SERVER_PORT:-8080}
      - SERVER_HOST=${SERVER_HOST:-0.0.0.0}
      - MINIO_USE_SSL=${MINIO_USE_SSL:-false}
      - MAX_FILE_SIZE=${MAX_FILE_SIZE:-104857600}
    depends_on:
      minio:
        condition: service_healthy
    volumes:
      - ./uploads:/tmp/uploads

volumes:
  minio_data: 